### ISSUE TITLE
requirements issue

### ISSUE THREAD

**Issue by nimiology** [AliRn76/panther#17]
**Describe the bug**

**Expected behavior**
I can't install Panther with pip. I think the problem is that uvloop in requirements can't be installed for Windows.

**Desktop (please complete the following information):**
 - OS: windows10

**Additional context**
```
(env) E:\PycharmProjects\panther_test_project>pip install panther
Collecting panther
  Obtaining dependency information for panther from https://files.pythonhosted.org/packages/28/5a/92fc7906d6504777b8df2ea0b49d36e4a6d1fac0e512338eb9ccc51242fe/panther-1.7.15-py3-none-any.whl.metadata
  Using cached panther-1.7.15-py3-none-any.whl.metadata (7.8 kB)
Collecting bpython~=0.24 (from panther)
  Using cached bpython-0.24-py3-none-any.whl (194 kB)
Collecting bson~=0.5 (from panther)
  Using cached bson-0.5.10.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Collecting httptools~=0.5 (from panther)
  Obtaining dependency information for httptools~=0.5 from https://files.pythonhosted.org/packages/80/e6/158e8d56f6b4d29295cfa244f1e79a65d0987bb3941d36863e7f6e06e3b6/httptools-0.6.0-cp311-cp311-win_amd64.whl.metadata
  Using cached httptools-0.6.0-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting pantherdb~=1.2 (from panther)
  Obtaining dependency information for pantherdb~=1.2 from https://files.pythonhosted.org/packages/e0/54/1b2055bd59ecc1106ed0dfc27c1eb2c0fe113f629d381ea60ac4d9cb52b2/pantherdb-1.2.7-py3-none-any.whl.metadata
  Using cached pantherdb-1.2.7-py3-none-any.whl.metadata (3.3 kB)
Collecting pydantic~=2.0 (from panther)
  Obtaining dependency information for pydantic~=2.0 from https://files.pythonhosted.org/packages/1f/1a/71b404f9acb44402f5b581ade106e9219d6d83824d50943e630fc0ca12e5/pydantic-2.0.3-py3-none-any.whl.metadata
  Using cached pydantic-2.0.3-py3-none-any.whl.metadata (128 kB)
Collecting redis~=4.5 (from panther)
  Obtaining dependency information for redis~=4.5 from https://files.pythonhosted.org/packages/20/2e/409703d645363352a20c944f5d119bdae3eb3034051a53724a7c5fee12b8/redis-4.6.0-py3-none-any.whl.metadata
  Using cached redis-4.6.0-py3-none-any.whl.metadata (8.3 kB)
Collecting rich~=13.3 (from panther)
  Obtaining dependency information for rich~=13.3 from https://files.pythonhosted.org/packages/fc/1e/482e5eec0b89b593e81d78f819a9412849814e22225842b598908e7ac560/rich-13.4.2-py3-none-any.whl.metadata
  Using cached rich-13.4.2-py3-none-any.whl.metadata (18 kB)
Collecting uvicorn~=0.21 (from panther)
  Obtaining dependency information for uvicorn~=0.21 from https://files.pythonhosted.org/packages/5d/07/b9eac057f7efa56900640a233c1ed63db83568322c6bcbabe98f741d5289/uvicorn-0.23.1-py3-none-any.whl.metadata
  Using cached uvicorn-0.23.1-py3-none-any.whl.metadata (6.2 kB)
Collecting uvloop~=0.17 (from panther)
  Using cached uvloop-0.17.0.tar.gz (2.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Nima\AppData\Local\Temp\pip-install-qlnxjkz5\uvloop_b087e03c273944f18a6a45207d3eb8ef\setup.py", line 8, in <module>
          raise RuntimeError('uvloop does not support Windows at the moment')
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by AliRn76** [comment]
Thanks for the report, it should be fixed in '1.7.16'.
