### ISSUE TITLE
Panther shell not working on Windows

### ISSUE THREAD

**Issue by satyahbp** [AliRn76/panther#39]
**Describe the bug**
I tried running the Panther shell on Command Prompt in windows with the command given in documentation. 
The following error was raised:
`
(panther_test) D:\Python\testing_panther>panther shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\test\.conda\envs\panther_test\Scripts\bpython.exe\__main__.py", line 4, in <module>
  File "C:\Users\test\.conda\envs\panther_test\Lib\site-packages\bpython\curtsies.py", line 10, in <module>
    import curtsies
  File "C:\Users\test\.conda\envs\panther_test\Lib\site-packages\curtsies\__init__.py", line 4, in <module>
    from .window import FullscreenWindow, CursorAwareWindow
  File "C:\Users\test\.conda\envs\panther_test\Lib\site-packages\curtsies\window.py", line 30, in <module>
    from .termhelpers import Cbreak
  File "C:\Users\test\.conda\envs\panther_test\Lib\site-packages\curtsies\termhelpers.py", line 1, in <module>
    import tty
  File "C:\Users\test\.conda\envs\panther_test\Lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'
`

**Expected behavior**
Expected a shell to work.

**Environment:**
 - OS: Windows: 10
 - Python Version:  3.11.5
 - Panther Version: 3.0.1

**Additional context**
It seems like "termios" doesn't work on Windows, it only works on unix. 
I suggest to add a windows alternative.

**Comment by AliRn76** [comment]
Thank you for the report, I'm going to work on it ASAP 👍🏽
